resources:
  - name: mavenrepo
    type: GitRepo
    configuration:
      gitProvider: git_integration
      path: HarshMota99/pipelines-project-examples
      branches: 
        include: master
      buildon:
        commit: true


pipelines:
  - name: first_pipeline
    steps:
      - name: myFirstStep
        type: Bash
        execution:
          onExecute:
            - echo "hello world1"
